import { useState } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Form from "react-bootstrap/Form";

import { GreeterClient } from "protos/HelloworldServiceClientPb";
import { HelloRequest } from "protos/helloworld_pb";
import { Empty } from "google-protobuf/google/protobuf/empty_pb";

const client = new GreeterClient("http://localhost:8080", null, null);

const Home: NextPage = () => {
  const [name, setName] = useState("Alex");
  const [messages, setMessages] = useState("");

  const sayHelloFn = () => {
    const request = new HelloRequest();
    request.setName(name);
    client.sayHello(request, null, (err, response) => {
      if (err) {
        console.log(err);
      }
      setMessages(response.getMessage());
    });
  };

  const clearHelloHistory = () => {
    client.clearHelloHistory(new Empty(), null, (err, response) => {
      if (err) {
        console.log(err);
      }
      setMessages("");
    });
  };

  return (
    <div className="container p-3">
      <Head>
        <title>App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Form className="m-3">
        <Form.Group className="mb-3">
          <Form.Control
            onChange={(event) => {
              setName(event.target.value);
            }}
            defaultValue="Alex"
            type="text"
            placeholder="Enter your name"
          />
        </Form.Group>
      </Form>
      <button className="btn btn-warning m-3" onClick={sayHelloFn}>
        Say Hello To Server
      </button>
      <button className="btn btn-warning m-3" onClick={clearHelloHistory}>
        Clear Chat History
      </button>
      {messages && <div className="m-3">{`Server Said: ${messages}`}</div>}
    </div>
  );
};

export default Home;
