import { useState } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

import styles from "styles/Home.module.css";
import { GreeterClient } from "protos/HelloworldServiceClientPb";
import { HelloRequest } from "protos/helloworld_pb";
import { Empty } from "google-protobuf/google/protobuf/empty_pb";

const client = new GreeterClient("http://localhost:8080", null, null);

const Home: NextPage = () => {
  const [name, setName] = useState("Alex");
  const [messages, setMessages] = useState("");

  const sayHelloFn = () => {
    const request = new HelloRequest();
    request.setName(name);
    client.sayHello(request, null, (err, response) => {
      if (err) {
        console.log(err);
      }
      setMessages(response.getMessage());
    });
  };

  const clearHelloHistory = () => {
    client.clearHelloHistory(new Empty(), null, (err, response) => {
      if (err) {
        console.log(err);
      }
      setMessages("");
    });
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          <form>
            <input
              placeholder="Enter your name"
              type="text"
              defaultValue={name}
              onChange={(e) => setName(e.target.value)}
            />
          </form>
        </div>
        <div>
          <button onClick={sayHelloFn}>Say Hello To Server</button>{" "}
          <button onClick={clearHelloHistory}>Clear Hello History</button>
        </div>
        <div>{messages}</div>
      </main>
    </div>
  );
};

export default Home;
